var allData = [{
            name: "bulbasaur",
            number: 1,
            type1: "grass",
            type2: "poison",
            maxCP: 1071,
            maxHP: 82,
            baseStamina : 90,
            baseAttack : 126,
            baseDefense : 126,
            familyID :  1 ,
            candyToEvolve: 25,
            evoMultiplier: 1.6
},
{
            name: "ivysaur",
            number: 2,
            type1: "grass",
            type2: "poison",
            maxCP: 1632,
            maxHP: 106,
            baseStamina : 120,
            baseAttack : 156,
            baseDefense : 158,
            familyID :  1,
            candyToEvolve: 100,
            evoMultiplier: 1.7
},
{
            name: "venusaur",
            number: 3,
            type1: "grass",
            type2: "poison",
            maxCP: 2580,
            maxHP: 138,
            baseStamina : 160,
            baseAttack : 198,
            baseDefense : 200,
            familyID :  1
},
{
            name: "charmander",
            number: 4,
            type1: "fire",
            maxCP: 955,
            maxHP: 73,
            baseStamina : 78,
            baseAttack : 128,
            baseDefense : 108,
            familyID :  4 ,
            candyToEvolve: 25,
            evoMultiplier: 1.7
},
{
            name: "charmeleon",
            number: 5,
            type1: "fire",
            maxCP: 1557,
            maxHP: 103,
            baseStamina : 116,
            baseAttack : 160,
            baseDefense : 140,
            familyID :  4 ,
            candyToEvolve: 100,
            evoMultiplier: 1.7
},
{
            name: "charizard",
            number: 6,
            type1: "fire",
            type2: "flying",
            maxCP: 2602,
            maxHP: 135,
            baseStamina : 156,
            baseAttack : 212,
            baseDefense : 182,
            familyID :  4
},
{
            name: "squirtle",
            number: 7,
            type1: "water",
            maxCP: 1008,
            maxHP: 81,
            baseStamina : 88,
            baseAttack : 112,
            baseDefense : 142,
            familyID :  7 ,
            candyToEvolve: 25,
            evoMultiplier: 1.7
},
{
            name: "wartortle",
            number: 8,
            type1: "water",
            maxCP: 1582,
            maxHP: 105,
            baseStamina : 118,
            baseAttack : 144,
            baseDefense : 176,
            familyID :  7 ,
            candyToEvolve: 100,
            evoMultiplier: 1.7
},
{
            name: "blastoise",
            number: 9,
            type1: "water",
            maxCP: 2542,
            maxHP: 136,
            baseStamina : 158,
            baseAttack : 186,
            baseDefense : 222,
            familyID :  7
},
{
            name: "caterpie",
            number: 10,
            type1: "bug",
            maxCP: 443,
            maxHP: 82,
            baseStamina : 90,
            baseAttack : 62,
            baseDefense : 66,
            familyID :  10 ,
            candyToEvolve: 12,
            evoMultiplier: 1.1
},
{
            name: "metapod",
            number: 11,
            type1: "bug",
            maxCP: 477,
            maxHP: 90,
            baseStamina : 100,
            baseAttack : 56,
            baseDefense : 86,
            familyID :  10 ,
            candyToEvolve: 50,
            evoMultiplier: 3.05
},
{
            name: "butterfree",
            number: 12,
            type1: "bug",
            type2: "flying",
            maxCP: 1454,
            maxHP: 106,
            baseStamina : 120,
            baseAttack : 144,
            baseDefense : 144,
            familyID :  10
},
{
            name: "weedle",
            number: 13,
            type1: "bug",
            type2: "poison",
            maxCP: 449,
            maxHP: 75,
            baseStamina : 80,
            baseAttack : 68,
            baseDefense : 64,
            familyID :  13 ,
            candyToEvolve: 12,
            evoMultiplier: 1.1
},
{
            name: "kakuna",
            number: 14,
            type1: "bug",
            type2: "poison",
            maxCP: 485,
            maxHP: 82,
            baseStamina : 90,
            baseAttack : 62,
            baseDefense : 82,
            familyID :  13 ,
            candyToEvolve: 50,
            evoMultiplier: 3.05
},
{
            name: "beedrill",
            number: 15,
            type1: "bug",
            type2: "poison",
            maxCP: 1439,
            maxHP: 114,
            baseStamina : 130,
            baseAttack : 144,
            baseDefense : 130,
            familyID :  13
},
{
            name: "pidgey",
            number: 16,
            type1: "normal",
            type2: "flying",
            maxCP: 679,
            maxHP: 75,
            baseStamina : 80,
            baseAttack : 94,
            baseDefense : 90,
            familyID :  16 ,
            candyToEvolve: 12,
            evoMultiplier: 1.88
},
{
            name: "pidgeotto",
            number: 17,
            type1: "normal",
            type2: "flying",
            maxCP: 1223,
            maxHP: 111,
            baseStamina : 126,
            baseAttack : 126,
            baseDefense : 122,
            familyID :  16 ,
            candyToEvolve: 50,
            evoMultiplier: 1.75
},
{
            name: "pidgeot",
            number: 18,
            type1: "normal",
            type2: "flying",
            maxCP: 2091,
            maxHP: 143,
            baseStamina : 166,
            baseAttack : 170,
            baseDefense : 166,
            familyID :  16
},
{
            name: "rattata",
            number: 19,
            type1: "normal",
            maxCP: 581,
            maxHP: 59,
            baseStamina : 60,
            baseAttack : 92,
            baseDefense : 86,
            familyID :  19 ,
            candyToEvolve: 25,
            evoMultiplier: 2.65
},
{
            name: "raticate",
            number: 20,
            type1: "normal",
            maxCP: 1444,
            maxHP: 98,
            baseStamina : 110,
            baseAttack : 146,
            baseDefense : 150,
            familyID :  19
},
{
            name: "spearow",
            number: 21,
            type1: "normal",
            type2: "flying",
            maxCP: 686,
            maxHP: 75,
            baseStamina : 80,
            baseAttack : 102,
            baseDefense : 78,
            familyID :  21 ,
            candyToEvolve: 50,
            evoMultiplier: 2.65
},
{
            name: "fearow",
            number: 22,
            type1: "normal",
            type2: "flying",
            maxCP: 1746,
            maxHP: 114,
            baseStamina : 130,
            baseAttack : 168,
            baseDefense : 146,
            familyID :  21
},
{
            name: "ekans",
            number: 23,
            type1: "poison",
            maxCP: 824,
            maxHP: 67,
            baseStamina : 70,
            baseAttack : 112,
            baseDefense : 112,
            familyID :  23 ,
            candyToEvolve: 50,
            evoMultiplier: 2.2
},
{
            name: "arbok",
            number: 24,
            type1: "poison",
            maxCP: 1767,
            maxHP: 106,
            baseStamina : 120,
            baseAttack : 166,
            baseDefense : 166,
            familyID :  23
},
{
            name: "pikachu",
            number: 25,
            type1: "electric",
            maxCP: 887,
            maxHP: 67,
            baseStamina : 70,
            baseAttack : 124,
            baseDefense : 108,
            familyID :  25 ,
            candyToEvolve: 50,
            evoMultiplier: 2.3
},
{
            name: "raichu",
            number: 26,
            type1: "electric",
            maxCP: 2028,
            maxHP: 106,
            baseStamina : 120,
            baseAttack : 200,
            baseDefense : 154,
            familyID :  25
},
{
            name: "sandshrew",
            number: 27,
            type1: "ground",
            maxCP: 798,
            maxHP: 90,
            baseStamina : 100,
            baseAttack : 90,
            baseDefense : 114,
            familyID :  27 ,
            candyToEvolve: 50,
            evoMultiplier: 2.45
},
{
            name: "sandslash",
            number: 28,
            type1: "ground",
            maxCP: 1810,
            maxHP: 130,
            baseStamina : 150,
            baseAttack : 150,
            baseDefense : 172,
            familyID :  27
},
{
            name: "nidoran (F)",
            number: 29,
            type1: "poison",
            maxCP: 876,
            maxHP: 98,
            baseStamina : 110,
            baseAttack : 100,
            baseDefense : 104,
            familyID :  29 ,
            candyToEvolve: 25,
            evoMultiplier: 1.6
},
{
            name: "nidorina",
            number: 30,
            type1: "poison",
            maxCP: 1404,
            maxHP: 122,
            baseStamina : 140,
            baseAttack : 132,
            baseDefense : 136,
            familyID :  29 ,
            candyToEvolve: 100,
            evoMultiplier:1.8
},
{
            name: "nidoqueen",
            number: 31,
            type1: "poison",
            type2: "ground",
            maxCP: 2485,
            maxHP: 154,
            baseStamina : 180,
            baseAttack : 184,
            baseDefense : 190,
            familyID :  29
},
{
            name: "nidoran (M)",
            number: 32,
            type1: "poison",
            maxCP: 843,
            maxHP: 84,
            baseStamina : 92,
            baseAttack : 110,
            baseDefense : 94,
            familyID :  32 ,
            candyToEvolve: 25,
            evoMultiplier: 1.65
},
{
            name: "nidorino",
            number: 33,
            type1: "poison",
            maxCP: 1372,
            maxHP: 108,
            baseStamina : 122,
            baseAttack : 142,
            baseDefense : 128,
            familyID :  32 ,
            candyToEvolve: 100,
            evoMultiplier:1.8
},
{
            name: "nidoking",
            number: 34,
            type1: "poison",
            type2: "ground",
            maxCP: 2475,
            maxHP: 139,
            baseStamina : 162,
            baseAttack : 204,
            baseDefense : 170,
            familyID :  32
},
{
            name: "clefairy",
            number: 35,
            type1: "fairy",
            maxCP: 1200,
            maxHP: 122,
            baseStamina : 140,
            baseAttack : 116,
            baseDefense : 124,
            familyID :  35,
            candyToEvolve: 50,
            evoMultiplier: 2.05
},
{
            name: "clefable",
            number: 36,
            type1: "fairy",
            maxCP: 2397,
            maxHP: 162,
            baseStamina : 190,
            baseAttack : 178,
            baseDefense : 178,
            familyID :  35
},
{
            name: "vulpix",
            number: 37,
            type1: "fire",
            maxCP: 831,
            maxHP: 71,
            baseStamina : 76,
            baseAttack : 106,
            baseDefense : 118,
            familyID :  37 ,
            candyToEvolve: 50,
            evoMultiplier: 2.8
},
{
            name: "ninetales",
            number: 38,
            type1: "fire",
            maxCP: 2188,
            maxHP: 127,
            baseStamina : 146,
            baseAttack : 176,
            baseDefense : 194,
            familyID :  37
},
{
            name: "jigglypuff",
            number: 39,
            type1: "normal",
            type2: "fairy",
            maxCP: 917,
            maxHP: 193,
            baseStamina : 230,
            baseAttack : 98,
            baseDefense : 54,
            familyID :  039 ,
            candyToEvolve: 50,
            evoMultiplier: 1.85
},
{
            name: "wigglytuff",
            number: 40,
            type1: "normal",
            type2: "fairy",
            maxCP: 2177,
            maxHP: 233,
            baseStamina : 280,
            baseAttack : 168,
            baseDefense : 108,
            familyID :  039
},
{
            name: "zubat",
            number: 41,
            type1: "poison",
            type2: "flying",
            maxCP: 642,
            maxHP: 75,
            baseStamina : 80,
            baseAttack : 88,
            baseDefense : 90,
            familyID :  041 ,
            candyToEvolve: 50,
            evoMultiplier:3
},
{
            name: "golbat",
            number: 42,
            type1: "poison",
            type2: "flying",
            maxCP: 1921,
            maxHP: 130,
            baseStamina : 150,
            baseAttack : 164,
            baseDefense : 164,
            familyID :  041
},
{
            name: "oddish",
            number: 43,
            type1: "grass",
            type2: "poison",
            maxCP: 1148,
            maxHP: 82,
            baseStamina : 90,
            baseAttack : 134,
            baseDefense : 130,
            familyID :  043 ,
            candyToEvolve: 25,
            evoMultiplier:1.5
},
{
            name: "gloom",
            number: 44,
            type1: "grass",
            type2: "poison",
            maxCP: 1689,
            maxHP: 106,
            baseStamina : 120,
            baseAttack : 162,
            baseDefense : 158,
            familyID :  043 ,
            candyToEvolve: 100,
            evoMultiplier:1.5
},
{
            name: "vileplume",
            number: 45,
            type1: "grass",
            type2: "poison",
            maxCP: 2492,
            maxHP: 130,
            baseStamina : 150,
            baseAttack : 202,
            baseDefense : 190,
            familyID :  043
},
{
            name: "paras",
            number: 46,
            type1: "bug",
            type2: "grass",
            maxCP: 916,
            maxHP: 67,
            baseStamina : 70,
            baseAttack : 122,
            baseDefense : 120,
            familyID :  046 ,
            candyToEvolve: 50,
            evoMultiplier:2
},
{
            name: "parasect",
            number: 47,
            type1: "bug",
            type2: "grass",
            maxCP: 1747,
            maxHP: 106,
            baseStamina : 120,
            baseAttack : 162,
            baseDefense : 170,
            familyID :  046
},
{
            name: "venonat",
            number: 48,
            type1: "bug",
            type2: "poison",
            maxCP: 1029,
            maxHP: 106,
            baseStamina : 120,
            baseAttack : 108,
            baseDefense : 118,
            familyID :  048 ,
            candyToEvolve: 50,
            evoMultiplier:1.85
},
{
            name: "venomoth",
            number: 49,
            type1: "bug",
            type2: "poison",
            maxCP: 1890,
            maxHP: 122,
            baseStamina : 140,
            baseAttack : 172,
            baseDefense : 154,
            familyID :  048
},
{
            name: "diglett",
            number: 50,
            type1: "ground",
            maxCP: 456,
            maxHP: 27,
            baseStamina : 20,
            baseAttack : 108,
            baseDefense : 86,
            familyID :  050 ,
            candyToEvolve: 50,
            evoMultiplier:2.7
},
{
            name: "dugtrio",
            number: 51,
            type1: "ground",
            maxCP: 1168,
            maxHP: 67,
            baseStamina : 70,
            baseAttack : 148,
            baseDefense : 140,
            familyID :  050
},
{
            name: "meowth",
            number: 52,
            type1: "normal",
            maxCP: 756,
            maxHP: 75,
            baseStamina : 80,
            baseAttack : 104,
            baseDefense : 94,
            familyID :  052 ,
            candyToEvolve: 50,
            evoMultiplier: 2
},
{
            name: "persian",
            number: 53,
            type1: "normal",
            maxCP: 1631,
            maxHP: 114,
            baseStamina : 130,
            baseAttack : 156,
            baseDefense : 146,
            familyID :  052
},
{
            name: "psyduck",
            number: 54,
            type1: "water",
            maxCP: 1109,
            maxHP: 90,
            baseStamina : 100,
            baseAttack : 132,
            baseDefense : 112,
            familyID :  054 ,
            candyToEvolve: 50,
            evoMultiplier: 2.2
},
{
            name: "golduck",
            number: 55,
            type1: "water",
            maxCP: 2386,
            maxHP: 138,
            baseStamina : 160,
            baseAttack : 194,
            baseDefense : 176,
            familyID :  054
},
{
            name: "mankey",
            number: 56,
            type1: "fighting",
            maxCP: 878,
            maxHP: 75,
            baseStamina : 80,
            baseAttack : 122,
            baseDefense : 96,
            familyID :  056 ,
            candyToEvolve: 50,
            evoMultiplier: 2.2
},
{
            name: "primeape",
            number: 57,
            type1: "fighting",
            maxCP: 1864,
            maxHP: 114,
            baseStamina : 130,
            baseAttack : 178,
            baseDefense : 150,
            familyID :  056
},
{
            name: "growlithe",
            number: 58,
            type1: "fire",
            maxCP: 1335,
            maxHP: 98,
            baseStamina : 110,
            baseAttack : 156,
            baseDefense : 110,
            familyID :  058 ,
            candyToEvolve: 50,
            evoMultiplier: 2.3
},
{
            name: "arcanine",
            number: 59,
            type1: "fire",
            maxCP: 2983,
            maxHP: 154,
            baseStamina : 180,
            baseAttack : 230,
            baseDefense : 180,
            familyID :  058
},
{
            name: "poliwag",
            number: 60,
            type1: "water",
            maxCP: 795,
            maxHP: 75,
            baseStamina : 80,
            baseAttack : 108,
            baseDefense : 98,
            familyID :  60 ,
            candyToEvolve: 25,
            evoMultiplier: 1.7
},
{
            name: "poliwhirl",
            number: 61,
            type1: "water",
            maxCP: 1340,
            maxHP: 114,
            baseStamina : 130,
            baseAttack : 132,
            baseDefense : 132,
            familyID :  60 ,
            candyToEvolve: 100,
            evoMultiplier: 2
},
{
            name: "poliwrath",
            number: 62,
            type1: "water",
            type2: "fighting",
            maxCP: 2505,
            maxHP: 154,
            baseStamina : 180,
            baseAttack : 180,
            baseDefense : 202,
            familyID :  60
},
{
            name: "abra",
            number: 63,
            type1: "psychic",
            maxCP: 600,
            maxHP: 51,
            baseStamina : 50,
            baseAttack : 110,
            baseDefense : 76,
            familyID :  063 ,
            candyToEvolve: 25,
            evoMultiplier: 1.9
},
{
            name: "kadabra",
            number: 64,
            type1: "psychic",
            maxCP: 1131,
            maxHP: 75,
            baseStamina : 80,
            baseAttack : 150,
            baseDefense : 112,
            familyID :  063 ,
            candyToEvolve: 100,
            evoMultiplier: 1.5
},
{
            name: "alakazam",
            number: 65,
            type1: "psychic",
            maxCP: 1813,
            maxHP: 98,
            baseStamina : 110,
            baseAttack : 186,
            baseDefense : 152,
            familyID :  063
},
{
            name: "machop",
            number: 66,
            type1: "fighting",
            maxCP: 1089,
            maxHP: 122,
            baseStamina : 140,
            baseAttack : 118,
            baseDefense : 96,
            familyID :  066 ,
            candyToEvolve: 25,
            evoMultiplier: 1.6
},
{
            name: "machoke",
            number: 67,
            type1: "fighting",
            maxCP: 1760,
            maxHP: 138,
            baseStamina : 160,
            baseAttack : 154,
            baseDefense : 144,
            familyID :  066 ,
            candyToEvolve: 100,
            evoMultiplier: 1.7
},
{
            name: "machamp",
            number: 68,
            type1: "fighting",
            maxCP: 2594,
            maxHP: 154,
            baseStamina : 180,
            baseAttack : 198,
            baseDefense : 180,
            familyID :  066
},
{
            name: "bellsprout",
            number: 69,
            type1: "grass",
            type2: "poison",
            maxCP: 1117,
            maxHP: 90,
            baseStamina : 100,
            baseAttack : 158,
            baseDefense : 78,
            familyID :  069 ,
            candyToEvolve: 25,
            evoMultiplier: 1.55
},
{
            name: "weepinbell",
            number: 70,
            type1: "grass",
            type2: "poison",
            maxCP: 1723,
            maxHP: 114,
            baseStamina : 130,
            baseAttack : 190,
            baseDefense : 110,
            familyID :  069 ,
            candyToEvolve: 100,
            evoMultiplier: 1.6
},
{
            name: "victreebel",
            number: 71,
            type1: "grass",
            type2: "poison",
            maxCP: 2530,
            maxHP: 138,
            baseStamina : 160,
            baseAttack : 222,
            baseDefense : 152,
            familyID :  069
},
{
            name: "tentacool",
            number: 72,
            type1: "water",
            type2: "poison",
            maxCP: 905,
            maxHP: 75,
            baseStamina : 80,
            baseAttack : 106,
            baseDefense : 136,
            familyID :  072 ,
            candyToEvolve: 50,
            evoMultiplier: 2.5
},
{
            name: "tentacruel",
            number: 73,
            type1: "water",
            type2: "poison",
            maxCP: 2220,
            maxHP: 138,
            baseStamina : 160,
            baseAttack : 170,
            baseDefense : 196,
            familyID :  072
},
{
            name: "geodude",
            number: 74,
            type1: "rock",
            type2: "ground",
            maxCP: 849,
            maxHP: 75,
            baseStamina : 80,
            baseAttack : 106,
            baseDefense : 118,
            familyID :  074 ,
            candyToEvolve: 25,
            evoMultiplier: 1.75
},
{
            name: "graveler",
            number: 75,
            type1: "rock",
            type2: "ground",
            maxCP: 1433,
            maxHP: 98,
            baseStamina : 110,
            baseAttack : 142,
            baseDefense : 156,
            familyID :  074 ,
            candyToEvolve: 100,
            evoMultiplier: 1.7
},
{
            name: "golem",
            number: 76,
            type1: "rock",
            type2: "ground",
            maxCP: 2303,
            maxHP: 138,
            baseStamina : 160,
            baseAttack : 176,
            baseDefense : 198,
            familyID :  074
},
{
            name: "ponyta",
            number: 77,
            type1: "fire",
            maxCP: 1516,
            maxHP: 90,
            baseStamina : 100,
            baseAttack : 168,
            baseDefense : 138,
            familyID :  077 ,
            candyToEvolve: 50,
            evoMultiplier: 1.5
},
{
            name: "rapidash",
            number: 78,
            type1: "fire",
            maxCP: 2199,
            maxHP: 114,
            baseStamina : 130,
            baseAttack : 200,
            baseDefense : 170,
            familyID :  077
},
{
            name: "slowpoke",
            number: 79,
            type1: "water",
            type2: "psychic",
            maxCP: 1218,
            maxHP: 154,
            baseStamina : 180,
            baseAttack : 110,
            baseDefense : 110,
            familyID :  079 ,
            candyToEvolve: 50,
            evoMultiplier: 2.2
},
{
            name: "slowbro",
            number: 80,
            type1: "water",
            type2: "psychic",
            maxCP: 2597,
            maxHP: 162,
            baseStamina : 190,
            baseAttack : 184,
            baseDefense : 198,
            familyID :  079
},
{
            name: "magnemite",
            number: 81,
            type1: "electric",
            type2: "steel",
            maxCP: 890,
            maxHP: 51,
            baseStamina : 50,
            baseAttack : 128,
            baseDefense : 138,
            familyID :  81 ,
            candyToEvolve: 50,
            evoMultiplier: 2.2
},
{
            name: "magneton",
            number: 82,
            type1: "electric",
            type2: "steel",
            maxCP: 1879,
            maxHP: 90,
            baseStamina : 100,
            baseAttack : 186,
            baseDefense : 180,
            familyID :  81
},
{
            name: "farfetchd",
            number: 83,
            type1: "normal",
            type2: "flying",
            maxCP: 1263,
            maxHP: 94,
            baseStamina : 104,
            baseAttack : 138,
            baseDefense : 132,
            familyID :  83
},
{
            name: "doduo",
            number: 84,
            type1: "normal",
            type2: "flying",
            maxCP: 855,
            maxHP: 67,
            baseStamina : 70,
            baseAttack : 126,
            baseDefense : 96,
            familyID :  84 ,
            candyToEvolve: 50,
            evoMultiplier: 2.2
},
{
            name: "dodrio",
            number: 85,
            type1: "normal",
            type2: "flying",
            maxCP: 1836,
            maxHP: 106,
            baseStamina : 120,
            baseAttack : 182,
            baseDefense : 150,
            familyID :  84
},
{
            name: "seel",
            number: 86,
            type1: "water",
            maxCP: 1107,
            maxHP: 114,
            baseStamina : 130,
            baseAttack : 104,
            baseDefense : 138,
            familyID :  86 ,
            candyToEvolve: 50,
            evoMultiplier: 2
},
{
            name: "dewgong",
            number: 87,
            type1: "water",
            type2: "ice",
            maxCP: 2145,
            maxHP: 154,
            baseStamina : 180,
            baseAttack : 156,
            baseDefense : 192,
            familyID :  86
},
{
            name: "grimer",
            number: 88,
            type1: "poison",
            maxCP: 1284,
            maxHP: 138,
            baseStamina : 160,
            baseAttack : 124,
            baseDefense : 110,
            familyID :  88 ,
            candyToEvolve: 50,
            evoMultiplier: 2.5
},
{
            name: "muk",
            number: 89,
            type1: "poison",
            maxCP: 2602,
            maxHP: 177,
            baseStamina : 210,
            baseAttack : 180,
            baseDefense : 188,
            familyID :  88
},
{
            name: "shellder",
            number: 90,
            type1: "water",
            maxCP: 822,
            maxHP: 59,
            baseStamina : 60,
            baseAttack : 120,
            baseDefense : 112,
            familyID :  90 ,
            candyToEvolve: 50,
            evoMultiplier: 2.5
},
{
            name: "cloyster",
            number: 91,
            type1: "water",
            type2: "ice",
            maxCP: 2052,
            maxHP: 90,
            baseStamina : 100,
            baseAttack : 196,
            baseDefense : 196,
            familyID :  90
},
{
            name: "gastly",
            number: 92,
            type1: "ghost",
            type2: "poison",
            maxCP: 804,
            maxHP: 59,
            baseStamina : 60,
            baseAttack : 136,
            baseDefense : 82,
            familyID :  92 ,
            candyToEvolve: 25,
            evoMultiplier: 1.75
},
{
            name: "haunter",
            number: 93,
            type1: "ghost",
            type2: "poison",
            maxCP: 1380,
            maxHP: 82,
            baseStamina : 90,
            baseAttack : 172,
            baseDefense : 118,
            familyID :  92 ,
            candyToEvolve: 100,
            evoMultiplier: 1.75
},
{
            name: "gengar",
            number: 94,
            type1: "ghost",
            type2: "poison",
            maxCP: 2078,
            maxHP: 106,
            baseStamina : 120,
            baseAttack : 204,
            baseDefense : 156,
            familyID :  92
},
{
            name: "onix",
            number: 95,
            type1: "rock",
            type2: "ground",
            maxCP: 857,
            maxHP: 67,
            baseStamina : 70,
            baseAttack : 90,
            baseDefense : 186,
            familyID :  95
},
{
            name: "drowzee",
            number: 96,
            type1: "psychic",
            maxCP: 1075,
            maxHP: 106,
            baseStamina : 120,
            baseAttack : 104,
            baseDefense : 140,
            familyID :  96 ,
            candyToEvolve: 50,
            evoMultiplier: 2.1
},
{
            name: "hypno",
            number: 97,
            type1: "psychic",
            maxCP: 2184,
            maxHP: 146,
            baseStamina : 170,
            baseAttack : 162,
            baseDefense : 196,
            familyID :  96
},
{
            name: "krabby",
            number: 98,
            type1: "water",
            maxCP: 792,
            maxHP: 59,
            baseStamina : 60,
            baseAttack : 116,
            baseDefense : 110,
            familyID :  98 ,
            candyToEvolve: 50,
            evoMultiplier: 2.5
},
{
            name: "kingler",
            number: 99,
            type1: "water",
            maxCP: 1823,
            maxHP: 98,
            baseStamina : 110,
            baseAttack : 178,
            baseDefense : 168,
            familyID :  98
},
{
            name: "voltorb",
            number: 100,
            type1: "electric",
            maxCP: 839,
            maxHP: 75,
            baseStamina : 80,
            baseAttack : 102,
            baseDefense : 124,
            familyID :  100 ,
            candyToEvolve: 50,
            evoMultiplier: 2
},
{
            name: "electrode",
            number: 101,
            type1: "electric",
            maxCP: 1646,
            maxHP: 106,
            baseStamina : 120,
            baseAttack : 150,
            baseDefense : 174,
            familyID :  100
},
{
            name: "exeggcute",
            number: 102,
            type1: "grass",
            type2: "psychic",
            maxCP: 1099,
            maxHP: 106,
            baseStamina : 120,
            baseAttack : 110,
            baseDefense : 132,
            familyID :  102 ,
            candyToEvolve: 50,
            evoMultiplier: 2.8
},
{
            name: "exeggutor",
            number: 103,
            type1: "grass",
            type2: "psychic",
            maxCP: 2955,
            maxHP: 162,
            baseStamina : 190,
            baseAttack : 232,
            baseDefense : 164,
            familyID :  102
},
{
            name: "cubone",
            number: 104,
            type1: "ground",
            maxCP: 1006,
            maxHP: 90,
            baseStamina : 100,
            baseAttack : 102,
            baseDefense : 150,
            familyID :  104 ,
            candyToEvolve: 50,
            evoMultiplier: 1.7
},
{
            name: "marowak",
            number: 105,
            type1: "ground",
            maxCP: 1656,
            maxHP: 106,
            baseStamina : 120,
            baseAttack : 140,
            baseDefense : 202,
            familyID :  104
},
{
            name: "hitmonlee",
            number: 106,
            type1: "fighting",
            maxCP: 1492,
            maxHP: 90,
            baseStamina : 100,
            baseAttack : 148,
            baseDefense : 172,
            familyID :  106
},
{
            name: "hitmonchan",
            number: 107,
            type1: "fighting",
            maxCP: 1516,
            maxHP: 90,
            baseStamina : 100,
            baseAttack : 138,
            baseDefense : 204,
            familyID :  107
},
{
            name: "lickitung",
            number: 108,
            type1: "normal",
            maxCP: 1626,
            maxHP: 154,
            baseStamina : 180,
            baseAttack : 126,
            baseDefense : 160,
            familyID :  108
},
{
            name: "koffing",
            number: 109,
            type1: "poison",
            maxCP: 1151,
            maxHP: 75,
            baseStamina : 80,
            baseAttack : 136,
            baseDefense : 142,
            familyID :  109 ,
            candyToEvolve: 50,
            evoMultiplier: 1.1
},
{
            name: "weezing",
            number: 110,
            type1: "poison",
            maxCP: 2250,
            maxHP: 114,
            baseStamina : 130,
            baseAttack : 190,
            baseDefense : 198,
            familyID :  109
},
{
            name: "rhyhorn",
            number: 111,
            type1: "ground",
            type2: "rock",
            maxCP: 1182,
            maxHP: 138,
            baseStamina : 160,
            baseAttack : 110,
            baseDefense : 116,
            familyID :  111 ,
            candyToEvolve: 50,
            evoMultiplier: 2
},
{
            name: "rhydon",
            number: 112,
            type1: "ground",
            type2: "rock",
            maxCP: 2243,
            maxHP: 177,
            baseStamina : 210,
            baseAttack : 166,
            baseDefense : 160,
            familyID :  111
},
{
            name: "chansey",
            number: 113,
            type1: "normal",
            maxCP: 675,
            maxHP: 407,
            baseStamina : 500,
            baseAttack : 40,
            baseDefense : 60,
            familyID :  113
},
{
            name: "tangela",
            number: 114,
            type1: "grass",
            maxCP: 1739,
            maxHP: 114,
            baseStamina : 130,
            baseAttack : 164,
            baseDefense : 152,
            familyID :  114
},
{
            name: "kangaskhan",
            number: 115,
            type1: "normal",
            maxCP: 2043,
            maxHP: 177,
            baseStamina : 210,
            baseAttack : 142,
            baseDefense : 178,
            familyID :  115
},
{
            name: "horsea",
            number: 116,
            type1: "water",
            maxCP: 794,
            maxHP: 59,
            baseStamina : 60,
            baseAttack : 122,
            baseDefense : 100,
            familyID :  116 ,
            candyToEvolve: 50,
            evoMultiplier: 2.2
},
{
            name: "seadra",
            number: 117,
            type1: "water",
            maxCP: 1713,
            maxHP: 98,
            baseStamina : 110,
            baseAttack : 176,
            baseDefense : 150,
            familyID :  116
},
{
            name: "goldeen",
            number: 118,
            type1: "water",
            maxCP: 965,
            maxHP: 82,
            baseStamina : 90,
            baseAttack : 112,
            baseDefense : 126,
            familyID :  118 ,
            candyToEvolve: 50,
            evoMultiplier: 2.2
},
{
            name: "seaking",
            number: 119,
            type1: "water",
            maxCP: 2043,
            maxHP: 138,
            baseStamina : 160,
            baseAttack : 172,
            baseDefense : 160,
            familyID :  118
},
{
            name: "staryu",
            number: 120,
            type1: "water",
            maxCP: 937,
            maxHP: 59,
            baseStamina : 60,
            baseAttack : 130,
            baseDefense : 128,
            familyID :  120 ,
            candyToEvolve: 50,
            evoMultiplier: 2.4
},
{
            name: "starmie",
            number: 121,
            type1: "water",
            type2: "psychic",
            maxCP: 2182,
            maxHP: 106,
            baseStamina : 120,
            baseAttack : 194,
            baseDefense : 192,
            familyID :  120
},
{
            name: "mr. mime",
            number: 122,
            type1: "psychic",
            type2: "fairy",
            maxCP: 1345,
            maxHP: 69,
            baseStamina : 80,
            baseAttack : 154,
            baseDefense : 196,
            familyID :  122
},
{
            name: "scyther",
            number: 123,
            type1: "bug",
            type2: "flying",
            maxCP: 2073,
            maxHP: 122,
            baseStamina : 140,
            baseAttack : 176,
            baseDefense : 180,
            familyID :  123
},
{
            name: "jynx",
            number: 124,
            type1: "ice",
            type2: "psychic",
            maxCP: 1716,
            maxHP: 114,
            baseStamina : 130,
            baseAttack : 172,
            baseDefense : 134,
            familyID :  124
},
{
            name: "electabuzz",
            number: 125,
            type1: "electric",
            maxCP: 2119,
            maxHP: 114,
            baseStamina : 130,
            baseAttack : 198,
            baseDefense : 160,
            familyID :  125
},
{
            name: "magmar",
            number: 126,
            type1: "fire",
            maxCP: 2265,
            maxHP: 114,
            baseStamina : 130,
            baseAttack : 214,
            baseDefense : 158,
            familyID :  126
},
{
            name: "pinsir",
            number: 127,
            type1: "bug",
            maxCP: 2121,
            maxHP: 114,
            baseStamina : 130,
            baseAttack : 184,
            baseDefense : 186,
            familyID :  127
},
{
            name: "tauros",
            number: 128,
            type1: "normal",
            maxCP: 1844,
            maxHP: 130,
            baseStamina : 150,
            baseAttack : 148,
            baseDefense : 184,
            familyID :  128
},
{
            name: "magikarp",
            number: 129,
            type1: "water",
            maxCP: 262,
            maxHP: 43,
            baseStamina : 40,
            baseAttack : 42,
            baseDefense : 84,
            familyID :  129 ,
            candyToEvolve: 400,
            evoMultiplier: 10.5
},
{
            name: "gyarados",
            number: 130,
            type1: "water",
            type2: "flying",
            maxCP: 2688,
            maxHP: 162,
            baseStamina : 190,
            baseAttack : 192,
            baseDefense : 196,
            familyID :  129
},
{
            name: "lapras",
            number: 131,
            type1: "water",
            type2: "ice",
            maxCP: 2980,
            maxHP: 217,
            baseStamina : 260,
            baseAttack : 186,
            baseDefense : 190,
            familyID :  131
},
{
            name: "ditto",
            number: 132,
            type1: "normal",
            maxCP: 919,
            maxHP: 87,
            baseStamina : 96,
            baseAttack : 110,
            baseDefense : 110,
            familyID :  132
},
{
            name: "eevee",
            number: 133,
            type1: "normal",
            maxCP: 1077,
            maxHP: 98,
            baseStamina : 110,
            baseAttack : 114,
            baseDefense : 128,
            familyID :  133 ,
            candyToEvolve: 25,
            evoMultiplier: "eevee"
},
{
            name: "vaporeon",
            number: 134,
            type1: "water",
            maxCP: 2816,
            maxHP: 217,
            baseStamina : 260,
            baseAttack : 186,
            baseDefense : 168,
            familyID :  133
},
{
            name: "jolteon",
            number: 135,
            type1: "electric",
            maxCP: 2140,
            maxHP: 114,
            baseStamina : 130,
            baseAttack : 192,
            baseDefense : 174,
            familyID :  133
},
{
            name: "flareon",
            number: 136,
            type1: "fire",
            maxCP: 2643,
            maxHP: 114,
            baseStamina : 130,
            baseAttack : 238,
            baseDefense : 178,
            familyID :  133
},
{
            name: "porygon",
            number: 137,
            type1: "normal",
            maxCP: 1691,
            maxHP: 114,
            baseStamina : 130,
            baseAttack : 156,
            baseDefense : 158,
            familyID :  137
},
{
            name: "omanyte",
            number: 138,
            type1: "rock",
            type2: "water",
            maxCP: 1119,
            maxHP: 67,
            baseStamina : 70,
            baseAttack : 132,
            baseDefense : 160,
            familyID :  138 ,
            candyToEvolve: 50,
            evoMultiplier: 2.2
},
{
            name: "omastar",
            number: 139,
            type1: "rock",
            type2: "water",
            maxCP: 2233,
            maxHP: 122,
            baseStamina : 140,
            baseAttack : 180,
            baseDefense : 202,
            familyID :  138
},
{
            name: "kabuto",
            number: 140,
            type1: "rock",
            type2: "water",
            maxCP: 1104,
            maxHP: 59,
            baseStamina : 60,
            baseAttack : 148,
            baseDefense : 142,
            familyID :  140 ,
            candyToEvolve: 50,
            evoMultiplier: 2.2
},
{
            name: "kabutops",
            number: 141,
            type1: "rock",
            type2: "water",
            maxCP: 2130,
            maxHP: 106,
            baseStamina : 120,
            baseAttack : 190,
            baseDefense : 190,
            familyID :  140
},
{
            name: "aerodactyl",
            number: 142,
            type1: "rock",
            type2: "flying",
            maxCP: 2165,
            maxHP: 138,
            baseStamina : 160,
            baseAttack : 182,
            baseDefense : 162,
            familyID :  142
},
{
            name: "snorlax",
            number: 143,
            type1: "normal",
            maxCP: 3112,
            maxHP: 264,
            baseStamina : 320,
            baseAttack : 180,
            baseDefense : 180,
            familyID :  143
},
{
            name: "articuno",
            number: 144,
            type1: "ice",
            type2: "flying",
            maxCP: 2978,
            maxHP: 154,
            baseStamina : 180,
            baseAttack : 198,
            baseDefense : 242,
            familyID :  144
},
{
            name: "zapdos",
            number: 145,
            type1: "electric",
            type2: "flying",
            maxCP: 3114,
            maxHP: 154,
            baseStamina : 180,
            baseAttack : 232,
            baseDefense : 194,
            familyID :  145
},
{
            name: "moltres",
            number: 146,
            type1: "fire",
            type2: "flying",
            maxCP: 3240,
            maxHP: 154,
            baseStamina : 180,
            baseAttack : 242,
            baseDefense : 194,
            familyID :  146
},
{
            name: "dratini",
            number: 147,
            type1: "dragon",
            maxCP: 983,
            maxHP: 76,
            baseStamina : 82,
            baseAttack : 128,
            baseDefense : 110,
            familyID :  147 ,
            candyToEvolve: 25,
            evoMultiplier: 1.8
},
{
            name: "dragonair",
            number: 148,
            type1: "dragon",
            maxCP: 1747,
            maxHP: 108,
            baseStamina : 122,
            baseAttack : 170,
            baseDefense : 152,
            familyID :  147 ,
            candyToEvolve: 100,
            evoMultiplier: 2
},
{
            name: "dragonite",
            number: 149,
            type1: "dragon",
            type2: "flying",
            maxCP: 3500,
            maxHP: 155,
            baseStamina : 182,
            baseAttack : 250,
            baseDefense : 212,
            familyID :  147
},
{
            name: "mewtwo",
            number: 150,
            type1: "psychic",
            maxCP: 4144,
            maxHP: 179,
            baseStamina : 212,
            baseAttack : 284,
            baseDefense : 202,
            familyID :  150
},
{
            name: "mew",
            number: 151,
            type1: "psychic",
            maxCP: 3299,
            maxHP: 169,
            baseStamina : 200,
            baseAttack : 220,
            baseDefense : 220,
            familyID :  151
}];
